AppStateESS/homestead

boost/boost.php
boost/install.sql
boost/update.php
boost/updates/00-04-89
class/HMS_Room.php
class/RoomView.php
class/command/EditRoomCommand.php
templates/admin/edit_room.tpl

* Add field to HMS_Room for id of rlc reservation
* Add DB update script and update install.sql to add rlc reserved id to
hms_room table.
* Update RoomView and EditRoomCommand to show and save RLC reservation
field.

RLC Self Select

---

class/HMS_Movein_Time.php
class/HMS_Room.php
class/command/UpdateRoomFieldCommand.php
templates/admin/room_pager_by_floor.tpl

Update floor view to allow floor-level editing of room reservations. Refs #874

Add quick-selection for RLC room reservation

---

class/HMS_Room.php

Show room RLC reservation in Room page on FloorView.

---

class/HMS_Roommate.php
class/command/AdminAddRlcMembersCommand.php

Relax housing application requirement for admin adding RLC members

---

boost/boost.php
boost/install.sql
boost/updates/00-04-90.sql
class/ApplicationMenuBlockView.php
class/CommandContext.php
class/Docusign/RecipientView.php
class/FreshmenApplicationReview.php
class/HousingApplicationFactory.php
class/Student.php
class/Term.php
class/TermsConditionsAdminView.php
class/TestSOAP.php
class/command/AgreeToTermsCommand.php
class/command/BeginDocusignCommand.php
class/command/HousingApplicationConfirmCommand.php
class/command/HousingApplicationFormSubmitCommand.php
class/command/OffCampusWaitingListFormSaveCommand.php
class/command/ReApplicationFormSaveCommand.php
class/command/ReApplicationFormSubmitCommand.php
class/command/ReApplicationWaitingListFormSubmitCommand.php
class/command/SaveTermSettingsCommand.php
class/command/ShowFreshmenApplicationReviewCommand.php
class/command/ShowHousingApplicationFormCommand.php
class/command/ShowOffCampusWaitListApplicationCommand.php
class/command/ShowReApplicationCommand.php
class/command/ShowTermsAgreementCommand.php
templates/admin/TermsConditionsAdminView.tpl

interface elements for saving/viewing. Add db update script and bumb
version number to 0.4.90. Refs #891

Request parent signature for under-18 contracts

---

boost/boost.php
boost/permission.php
boost/update.php
boost/updates/00-04-92.sql
class/CheckinFactory.php
class/DamageTypeFactory.php
class/HMS_Email.php
class/HMS_Permission.php
class/HMS_Residence_Hall.php
class/PdoFactory.php
class/RoomDamage.php
class/RoomDamageFactory.php
class/RoomDamageResponsibilityFactory.php
class/ServiceDeskMenu.php
class/command/CheckoutFormSubmitCommand.php
class/command/SendRoomDamageNotificationsCommand.php
templates/email/roomDamageNotice.tpl

Add feature for sending email notifications to students who have assessed (and billed) room damages after they checked out.

Room damage notices

---

class/report/GenderDistributionByHall/GenderDistributionByHall.php
class/report/GenderDistributionByHall/GenderDistributionByHallHtmlView.php
templates/admin/reports/GenderDistributionByHall.tpl

Added a coed and coed percentage column to Gender Distribution By Hall Report

Added a coed and coed percentage column to Gender Distribution By Hall Report

---

class/report/CoedRooms/CoedRooms.php
class/report/CoedRooms/CoedRoomsController.php
class/report/CoedRooms/CoedRoomsHtmlView.php
templates/admin/reports/CoedRooms.tpl

Created coed rooms report refs #783

Created new report to display Coed Rooms. refs #783

---

class/WKPDF.php
composer.json

Composer now requires WKPDF

---

class/WaitingListApplication.php

As per Jeremy's instructions to fix the error ocurring on Open Waiting List.

Changed waitingListPage() in WaitingListApplication to static

---

boost/install.sql
class/RoomChangeListView.php
class/WaitingListApplication.php
templates/admin/roomChangeListView.tpl
templates/student/roomChangeRequestForm.tpl

Updates to the Room Change List view and template in order to update with bootstrap components.

Admin room change list

---

class/RoomChangeParticipantView.php
class/WaitingListApplication.php

Check in error on room change

---

class/RlcRosterPager.php
class/ShowViewByRlc.php
templates/admin/view_by_rlc_pager.tpl

The roommate sorting works kinda....

Sort rlc roster issue932

---

class/ProfileHousingAppList.php
class/command/CancelHousingApplicationCommand.php
templates/admin/profileHousingAppList.tpl

Student profile cancel

---

class/report/CancelledAppsByType/CancelledAppsByTypeHtmlView.php

The file was using two different variable names for total cancellations.

---

class/report/EarlyRelease/EarlyRelease.php
class/report/EarlyRelease/EarlyReleaseController.php
class/report/EarlyRelease/EarlyReleaseHtmlView.php
templates/admin/reports/EarlyRelease.tpl

Created a report for students who are planning to apply for early release. Refs #936

Created Early Release Report

---

class/report/RaReport/RaReport.php
class/report/RaReport/RaReportController.php
class/report/RaReport/RaReportHtmlView.php
templates/admin/reports/RaReport.tpl

Created a report of every RA on campus for the current term

---

class/report/MismatchedRoommates/MismatchedRoommates.php
class/report/MismatchedRoommates/MismatchedRoommatesController.php
class/report/MismatchedRoommates/MismatchedRoommatesHtmlView.php
templates/admin/reports/MismatchedRoommates.tpl

Created report for roommates who are not matched with their requested roommates. Refs #861

Mismatched Roommates Report

---

class/AddRoomView.php
class/HMS_Floor.php
class/command/AddRoomCommand.php
templates/admin/add_new_room.tpl

Created a new template for adding a new room, and updated the view to use bootstrap.
Refs #1017

Update 'Add Room' View

---

class/AddBedView.php
class/HMS_Activity_Log.php
class/ProfileHousingAppList.php
class/command/ReinstateApplicationCommand.php
inc/defines.php
templates/admin/add_bed.tpl
templates/admin/profileHousingAppList.tpl

Refs #915
Also includes bootstrapping Add Bed View

Made a template for a page for adding beds. Made changes to AddBedView.

---

boost/update.php
boost/updates/00-05-02.sql
class/FallApplication.php
class/HousingApplication.php
class/PreferencesRoommatePairingStrategy.php

Pairings by smoking pref

---

class/HousingApplication.php
class/command/HousingApplicationConfirmCommand.php

When an edited version of the application is being added it now saves the old created on date and created by and places those values into the new application that goes into the database.
Refs #862

Save application submission date on edit

---

class/report/NoShowList/NoShowList.php
templates/admin/reports/NoShowList.tpl
templates/student/student_application.tpl

Made changes to the formatting of the template and added red flags to indicate required fields.
Refs #799 - Required fields on housing app
Refs #820 - No Show Report

Required Fields on App & No Show Report

---

class/HMS_RLC_Assignment.php

Was checking incorrect variable cellPhone, now checks housingApp. Refs #1040

Fix undefined var $cellPhone in HMS_RLC_Application

---

class/report/AppliedStudentData/AppliedStudentData.php

Added a column for Lifestyle in the Applied Student Data Export Report.

---

class/command/RequestRoommateCommand.php

Added a timestamp to the log for when a roommate request expires.

---

class/report/AssignedStudentData/AssignedStudentData.php

Update AssignedStudentData report to user bannerIDs instead of usernames for lookups.

Update AssignedStudentData report to user bannerIDs

---

boost/updates/00-05-05.sql
class/HMS_Room.php
class/RoomView.php
class/command/EditRoomCommand.php
templates/admin/edit_room.tpl

Add room reservation reasons dropdown

---

class/HMS_Residence_Hall.php
class/report/ReappAvailableBeds/ReappAvailableBeds.php
class/report/ReappAvailableBeds/ReappAvailableBedsController.php
class/report/ReappAvailableBeds/ReappAvailableBedsHtmlView.php
templates/admin/reports/ReappAvailableBeds.tpl

Reapp avail report

---

class/PhpSOAP.php
class/RoomDamage.php
class/RoomDamageFactory.php
class/RoomDamageResponsibility.php
class/SOAP.php
class/TestSOAP.php
class/command/AssessRoomDamageCommand.php
javascript/damageAssessment/DamageAssessment.jsx

Add support for reporting room damages directly to student accounts

---

class/report/AppliedStudentData/AppliedStudentData.php
class/report/AssignedStudentData/AssignedStudentData.php

Creates preferred name into Assigned Student Data report.

Add preferred name field to Assigned Student Data report.

---

class/report/CheckoutList/CheckoutList.php
class/report/CheckoutList/CheckoutListController.php
class/report/CheckoutList/CheckoutListHtmlView.php
templates/admin/reports/CheckoutList.tpl

Added a report for listing the Checkouts for the term.

---

class/PackageDeskFactory.php
class/ResidenceHallView.php
class/command/EditResidenceHallCommand.php
templates/admin/edit_residence_hall.tpl

Added an option to select Package Desk for Fedex packages #595

---

class/HallOverview.php

Use getStudentByBannerId() when looking up students for the HallOverview

---

class/BannerRoomChangeStudent.php
class/HMS_Activity_Log.php
class/HMS_Assignment.php
class/PhpSOAP.php
class/SOAP.php
class/SOAPDataProvider.php
class/TestSOAP.php
class/command/RoomChangeApproveCommand.php
class/exception/BannerException.php
inc/defines.php

Add support for moveRoomAssignment endpoint in the SOAP/web service classes and use it to reassign students when a room change is approved (so that billing can be prorated in Banner).
Refs #875

Prorate Room Change Charges

---

class/Docusign/Envelope.php
class/DocusignClientFactory.php
class/ProfileHousingAppList.php
class/StudentProfileView.php
templates/admin/profileHousingAppList.tpl

Changed the view and cancel application on the student profiles application list into a dropdown, and then added a link to view the docusign contract.
Cherry-picked from #1117

Add DocuSign View Link to Student Profile

---

class/Docusign/Envelope.php
class/DocusignClientFactory.php
class/ProfileHousingAppList.php
templates/admin/profileHousingAppList.tpl
templates/student/special_needs.tpl

View contract on student profile

---

boost/boost.php
boost/install.sql
boost/update.php
boost/updates/00-05-09.sql
class/Contract.php
class/ContractFactory.php
class/Docusign/Envelope.php
class/command/BeginDocusignCommand.php
contrib/updateDocusignContractStatus.php

Keep track of each contract's envelope status in DocuSign. Add a script to double check the status of all contracts and update the local database.

Track DocuSign Envelope Status & Add update script

---

class/command/LotteryChooseRoommatesCommand.php
class/command/ShowReApplicationCommand.php
class/command/ShowTermsAgreementCommand.php

Contract flow reordering

---

class/report/ApplicationsWithIncompleteContracts/ApplicationsWithIncompleteContracts.php
class/report/ApplicationsWithIncompleteContracts/ApplicationsWithIncompleteContractsController.php
class/report/ApplicationsWithIncompleteContracts/ApplicationsWithIncompleteContractsHtmlView.php
templates/admin/reports/ApplicationsWithIncompleteContracts.tpl

Add Applications With Incomplete Contracts Report

---

boost/boost.php
boost/install.sql
boost/update.php
boost/updates/00-05-10.sql
class/ReApplicationOffCampusFormView.php
class/WaitingListApplication.php
class/command/OffCampusWaitingListFormSaveCommand.php
class/command/ShowOffCampusWaitListApplicationCommand.php
templates/student/reapplicationOffcampus.tpl

Update the Open Waiting List housing application:
* Remove DocuSign contract (will only request contract signature if offered housing)
* Add additional questions for why the student is applying to the waiting list and why they need on-campus housing
* Fix other minor bugs and inconsistencies (remove old disability flags, update phone number handling, etc)

Update open wait list

---

class/command/ShowStudentMenuCommand.php

Added a check to make sure the gender field is either M or F.

---

boost/install.sql

Changed the install.sql file where the code was failing.

fixed install sql problems

---

class/BedView.php
class/FakeSoapTable.php
class/HMSFactory.php
class/HMS_Roommate.php
class/NightlyCache.php
class/PdoFactory.php
composer.json
composer.lock
index.php

…Apache-specifc and not supported under Nginx.

Updates for nginx on RHEL 7

---

class/report/PackageDeskExport/PackageDeskExport.php

Added preferred name to the PackageDeskExport class

---

class/FakeSoapTable.php
class/HMS_Activity_Log.php
class/HMS_Roommate.php
class/PdoFactory.php
class/command/SendRoomDamageNotificationsCommand.php
inc/defines.php

Entry now gets added when sending damage notification email 

---

class/CheckoutFormView.php
templates/admin/CheckOut.html

Added sanatation to key code input in CheckoutFormView through JSON to prevent xss-scripting

---

class/ApplicationFeature/Application.php
class/ApplicationFeature/ReappWaitingList.php
class/ApplicationFeature/Reapplication.php
class/ApplicationFeature/RlcReapplication.php
class/Command/LotteryConfirmCommand.php
class/Command/LotteryConfirmRoommateRequestCommand.php
class/Command/LotteryShowRoommateRequestCommand.php
class/Command/OpenWaitingListRemoveCommand.php
class/Command/ShowEmergencyContactFormCommand.php
class/Command/ShowHousingApplicationFormCommand.php
class/Command/ShowOffCampusWaitListApplicationCommand.php
class/Command/ShowRlcReapplicationCommand.php
class/Command/SubmitRLCReapplicationPage2Command.php
class/Command/WaitingListRemoveCommand.php
class/LotteryChooseRoommatesView.php
class/WithdrawnSearch.php

#1155 -Deprecated the use of HousingApplication::getApplicationByUser and replaced it with HousingApplicationFactory::getAppByStudent

Removed the use of HousingApplication::getApplicationByUser

---

class/Command/EmergencyContactConfirmCommand.php
class/EmergencyContactFormView.php
templates/css/bootstrap.css
templates/css/hms.css
templates/student/contact_page.tpl
templates/student/emergency_contact_form.tpl

Allows students to change phone number in emergency contact page

---

class/CheckoutFormView.php
class/Command/ShowOffCampusWaitListApplicationCommand.php
class/Command/ShowRoomDamageAssessmentCommand.php
class/FakeSoapTable.php
class/GuestHMS.php
class/GuestView.php
class/HMS_Email.php
class/ReApplicationFormView.php
javascript/CheckOut/CheckOut.jsx
javascript/StudentAddRoomDamages/roomDamage.jsx
templates/admin/dashboardHome.tpl
templates/guest.tpl
templates/misc/login.tpl
templates/student/reapplicationForm.tpl
templates/student/student_application.tpl

I changed the layout of the guest log-in, fixed some problems with checkout and adding room damages, and changed some of the applications so you can now see the checkboxes.
I commented out the calls to logSwiftmailMessageLong in HMS_Email since the function was commented out.
I also changed one of the graphs on the dashboard page to make it more hms related since it was about cars. (I can take it out if needed)

Some fixes to the nav

---

class/Command/GetHallCardListCommand.php
class/ResidenceHallView.php
class/SelectHallView.php
entryPoints.js
javascript/hallCardList/hallCardList.jsx
javascript/rlcCardList/rlcCardList.jsx
templates/admin/edit_residence_hall.tpl
templates/admin/select_residence_hall.tpl

Made cards for each all with the picture of each all the exterior image uploaded. The newland picture is set if there is no picture uploaded for the hall. There is a set min height for the cards so they resize nicer with 4 cards for large, 2 for medium and small, and 1 for extra small. A donut graph is on the card that shows the percent full for each hall with current colors gray(empty) and blue(full). On the edit hall page a hall banner has been added with the name of the hall over the picture. The picture has a set height and the width fills to the edge of the table below it.

Card halls

---

boost/update.php
boost/updates/00-05-14.sql
class/EmailLogFactory.php
class/HMS_Email.php
class/Scheduled/UpdateMandrillInfo.php
cli.php

Added mandrill script to the Schedule folder as well as updated the email log factory to accept new requirements. Update sql script reflects these changes and enabled the cli.php to take multiple class arguments.

Email data madrill
